### ISSUE TITLE
#ID带_0的无法下载

### ISSUE THREAD

**Issue by ujmyvq1582** [xing-yv/7mao-novel-downloader#12]
地址如下，使用debug模式提示404，怀疑是程序没有处理最后的_0导致。
https://www.qimao.com/shuku/1260880_0/

**Comment by shing-yu** [comment]
ID带0的为新书，在网页上阅读不需要会员的那种
程序刚开始开发时研究过，这样的书籍不管怎么处理
（去_0，去_）
均无法正常请求API
需等待书籍ID的0消失后才可以下载
（24小时未回复将被关闭）
