### ISSUE TITLE
大佬mac如何使用，需要装python吗，直接安装点击提示不可用

### ISSUE THREAD

**Issue by Lvqx** [xing-yv/7mao-novel-downloader#13]
![WX20240305-164338@2x](https://github.com/shing-yu/7mao-novel-downloader/assets/24424226/88b6f495-b146-469e-b4d6-084c435cebb2)

**Comment by shing-yu** [comment]
关于此文件的运行方式，您可以搜索“mac运行unix可执行文件”，或加入群聊查看视频教程
