### ISSUE TITLE
bug: 华为云镜像故障

### ISSUE THREAD

**Issue by q869939686** [xing-yv/7mao-novel-downloader#14]
raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://mirrors.huaweicloud.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <html>
执行报错

**Comment by shing-yu** [comment]
华为云镜像故障，等待修复
