### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by ikun14514** [xing-yv/7mao-novel-downloader#15]
发生异常:
C:\Users\p8877665\Downloads\7mao_tool_windows.exe appears to have been moved or deleted since this application was launched. Continouation from this state is impossible. Exiting now.
正在尝试保存文件...
文件已保存！
Exception ignored in: <function tqdm.__del__ at 0x000001D24D82DF80>
Traceback (most recent call last):
  File "tqdm\std.py", line 1148, in __del__
  File "tqdm\std.py", line 1267, in close
AttributeError: 'tqdm' object has no attribute 'disable'

**Comment by shing-yu** [comment]
**请注意：错误信息显示您在程序运行时删除或移动了程序文件，这是不允许的；如果您并未进行此操作，请按以下步骤操作**

**检查运行时除了火绒安全之外的安全软件是否正在运行（包括Windows Defender），如果是，请关闭它们并重试** 

如果仍然无法解决，请提供：
1. 系统信息
2. 出错的小说的链接/ID
3. 程序版本
4. 是否有其他异常情况

如果您在使用Windows操作系统，最好按照以下步骤提供dxdiag.txt：

1. 在Windows系统中，按下 `Win + R` 组合键打开“运行”对话框。
2. 输入 `dxdiag` 并按下回车键打开“DirectX 诊断工具”。
3. 在“DirectX 诊断工具”窗口中，单击“保存所有信息”按钮。
4. 选择保存位置，并将保存的文件命名为 `dxdiag.txt`。
5. 将您保存的 `dxdiag.txt` 文件附加到此issue中。

**Comment by ikun14514** [comment]
之前使用的是云电脑运行 使用的是windows sever系统 可能是环境问题 换到我自己电脑上解决了 感谢开发者
