### ISSUE TITLE
章节和内容对不上

### ISSUE THREAD

**Issue by sadforver** [xing-yv/7mao-novel-downloader#16]
示例ID：1710753

**Comment by shing-yu** [comment]
这是七猫那边的问题，似乎bookID重复了还是什么，反正返回就是这样，我也无能为力

**Comment by shing-yu** [comment]
发现有Mac用户报告同问题，Reopen一下  
你是什么系统？

**Comment by Smaritron** [comment]
MacBook Air M2，macOS 14.4.1，发现同样的问题

**Comment by shing-yu** [comment]
受该bug影响的用户可暂时回退至3.0.0版本

**Comment by kelle-j** [comment]
同样的id，用4.0版本下载下来目录跟内容对不上，3.0是可以对上的，希望把4.0优化下

**Comment by shing-yu** [comment]
> 同样的id，用4.0版本下载下来目录跟内容对不上，3.0是可以对上的，希望把4.0优化下

你是mac吗？

**Comment by kelle-j** [comment]
> > 同样的id，用4.0版本下载下来目录跟内容对不上，3.0是可以对上的，希望把4.0优化下
> 
> 你是mac吗？
不是，windows的

**Comment by caiabc** [comment]
我也遭遇了章节号和内容对不上的问题。
书籍ID：143185
名称：一剑独尊
作者：青鸾峰上

第两千两百九十章：谁敢称无敌？实际内容跑到了“第一百四十八章”

**Comment by shing-yu** [comment]
> > > 同样的id，用4.0版本下载下来目录跟内容对不上，3.0是可以对上的，希望把4.0优化下
> > 
> > 
> > 你是mac吗？
> > 不是，windows的

请提供一下系统内部版本（如22631.3672等）或dxdiag.txt文件（按Win+R，输入dxdiag回车执行，点击保存所有信息）

**Comment by shing-yu** [comment]
> 我也遭遇了章节号和内容对不上的问题。 书籍ID：143185 名称：一剑独尊 作者：青鸾峰上
> 
> 第两千两百九十章：谁敢称无敌？实际内容跑到了“第一百四十八章”

请提供一下操作系统和版本

**Comment by shing-yu** [comment]
已修复，今天发版
