### ISSUE TITLE
请教一下：下载的小说，内容与章节错乱了，请问是什么问题（另一本又没问题）

### ISSUE THREAD

**Issue by AaronKarrenE** [xing-yv/7mao-novel-downloader#18]
![image](https://github.com/shing-yu/7mao-novel-downloader/assets/172993396/47b2431c-541b-4839-9a86-7ff7a3d6673d)
![image](https://github.com/shing-yu/7mao-novel-downloader/assets/172993396/71c2e50c-c198-4cd9-96a1-cbf00c576417)
  以上是官网和下载下来的内容对比，
![image](https://github.com/shing-yu/7mao-novel-downloader/assets/172993396/d269612e-fd79-46db-a9c9-720aeec0c160)
以上是我用的工具，电脑是win10

**Comment by shing-yu** [comment]
#16
