### ISSUE TITLE
章节和内容对不上

### ISSUE THREAD

**Issue by caiabc** [xing-yv/7mao-novel-downloader#19]
在#16 issues中，我提到了

_

> 章节和内容对不上
> 
> 书籍ID：143185
> 名称：一剑独尊
> 作者：青鸾峰上
> 
> 第两千两百九十章：谁敢称无敌？实际内容跑到了“第一百四十八章”

_

感谢修复了原来的问题。
今天，我下载了修复后的新版本，试试重新下载结果如何？

先说明，我在6月8日，用3.0版本的下载器，完整下载了“一剑独尊” 这本书，内容和直接网页看，是对得上的，所以，结论是老版本的3.0下载器，是能够正常工作的。

今天，使用修复后的SLQimaoDownloaderWindows，4.01版本，还是下载> 书籍ID：143185
> 名称：一剑独尊

下载后，我用文本对比工具，将用3.0下载工具和4.0下载工具获得的文本对比了一下，发现有新的章节和内容对不上问题。

具体如下：

第两千零九十七章：别为难我了！
该章节的文本，在4.0版本错误映射到了下一章节的正文。

往下好几个章节，就被错位了一个章节，然后，在
第两千零九十九章：滚！
内容映射到了前面错乱了的第两千零九十七章的真实内容文本。

再往后，第两千一百章：谁给你的勇气？就开始正常了。

如有空，请检查原因。

**Comment by caiabc** [comment]
我在Microsoft Windows [版本 10.0.17763.1098]  下运行

使用的 v4.0.1

**Comment by shing-yu** [comment]
由于Github Action的配额上限，4.0.2版本将于7月1日发布，可通过邮件或QQ等方式联系我获取Windows平台的Beta版
