### ISSUE TITLE
无法进行批量下载

### ISSUE THREAD

**Issue by MachMY** [xing-yv/7mao-novel-downloader#6]
只用过2.8.3和2.8.6版本
均可以进行单次下载,批量更新,单次更新，但无法进行批量下载,会出现以下报错
![Screenshot 2023-11-26 204127](https://github.com/xing-yv/7mao-novel-downloader/assets/145979774/ba4f1ef2-4367-49a6-9f83-4843215b78d9)

**Comment by shing-yu** [comment]
抱歉，批量模式检测代码忘记改了，这就hotfix QAQ

**Comment by shing-yu** [comment]
已于2.8.6-post.1版本修复
